### ISSUE TITLE
PR from user https://github.com/add-twistlock/twistcli-scan-image-orb/pull/5

### ISSUE THREAD

**Issue by jpadams** [twistlock/sample-code#150]
@gunjan5 Hi! I'm a former Twistlock/PANW person who wrote a CircleCI orb (it seems 😆) in the past, and a user has contributed a PR that I can't merge. Not sure if you can help. Cheers!

https://github.com/add-twistlock/twistcli-scan-image-orb/pull/5

**Comment by sgordon46** [comment]
Try the new sample code location:

https://github.com/PaloAltoNetworks/prisma-cloud-compute-sample-code
