### ISSUE TITLE
Extended informaiton on Marketplace Azure DevOps

### ISSUE THREAD

**Issue by msfe** [twistlock/sample-code#26]
Hey,

For [marketplace](https://marketplace.visualstudio.com/items?itemName=Twistlock.twistcli-build-release-task&ssr=false#overview) the information would need to be updated. The link to source is not working. Also it would be great to link to license from marketplace right hand menu under resources, such as in [Replace Tokens](https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens)

**Comment by jpadams** [comment]
@msfe thanks for that. We'll update the listing and take a look at providing a license link.

**Comment by jpadams** [comment]
Links fixed. Thanks, @msfe ! 

https://github.com/twistlock/sample-code/tree/master/CI/Azure_DevOps/Extensions/azure-devops-twistcli-tasks
