### ISSUE TITLE
Azure DevOps plugin requires the setting of vulnerability and compliance thresholds

### ISSUE THREAD

**Issue by mklambert** [twistlock/sample-code#30]
The Azure DevOps plugin requires that the vulnerability and compliance thresholds be set to "low," "medium," "high," or "critical." This prevents the plugin from running in a fully non-blocking mode, which is a legitimate invocation of twistcli. The thresholds should offer a "none" option that, if selected, causes the `--vulnerability-threshold` and `--compliance-threshold` flags to be omitted from the argument list to twistcli.

**Comment by zoemac11** [comment]
Is this still be owned by someone? I haven't noticed any updates since 2019

**Comment by wfg** [comment]
@zoemac11 I believe the [Twistlock plugin](https://marketplace.visualstudio.com/items?itemName=Twistlock.twistcli-build-release-task) should be replaced with the [Prisma Cloud plugin](https://marketplace.visualstudio.com/items?itemName=Palo-Alto-Networks.build-release-task).

I was about to begin addressing this issue, but the Prisma Cloud plugin already handles image scanning, so it seems it's been taken a different direction.
