### ISSUE TITLE
[Splunk App] Create app setup page

### ISSUE THREAD

**Issue by wfg** [twistlock/sample-code#32]
https://dev.splunk.com/enterprise/docs/developapps/manageknowledge/setuppage

Currently, the user must manually edit `config.json` to add credentials and the Console URL. Create a setup page so the user is able to configure it in the Splunk web UI upon app installation.

- [x] Ability to provide all configuration (everything in `config.json`) in setup UI
- [x] Utilize encrypted storage for sensitive configuration items (`console.password`)

**Comment by jeromecartagena** [comment]
Eagerly anticipating this Issue to be resolved.

https://docs.splunk.com/Documentation/Splunk/6.3.2/AdvancedDev/SetupExampleCredentials

**Comment by wfg** [comment]
@jeromecartagena I have a setup page working. Would you like to test it and provide feedback? If so, please shoot me an email (wgill at paloaltonetworks.com).
