### ISSUE TITLE
on operator install in openshift I get InvalidImageName

### ISSUE THREAD

**Issue by anolan80** [twistlock/sample-code#63]
consoleImageName: registry-auth.twistlock.com/tw_<REPLACE_TWISTLOCK_TOKEN>/twistlock/console:console_20_04_163

but I changed the values in the CR that should have been replaced.

88s         Warning   OverrideValuesInUse      twistlockconsole/twistlockconsole                                    Chart value "consoleImageName" overridden to "registry-auth.twistlock.com/tw_<REPLACE_TWISTLOCK_TOKEN>/twistlock/console:console_20_04_169" by operator's watches.yaml
68s         Warning   OverrideValuesInUse      twistlockconsole/twistlockconsole                                    Chart value "consoleImageName" overridden to "registry-auth.twistlock.com/tw_<REPLACE_TWISTLOCK_TOKEN>/twistlock/console:console_20_04_169" by operator's watches.yaml

**Comment by anolan80** [comment]
I over-rode the values in the CSR to fix this issue to come back with
         Warning   Failed                   pod/twistlock-console-kd2vs                                          Failed to pull image "registry-auth.twistlock.com/tw_xxxxxxxxxxxxxxxxxxxx/twistlock/console:console_20_04_169": rpc error: code = Unknown desc = Error reading manifest console_20_04_169 in registry-auth.twistlock.com/tw_xxxxxxxxxxxxxxxxxx/twistlock/console: unauthorized: authentication required

**Comment by kitforbes** [comment]
The value we provide in the CR seems to be ignored and is replaced by [this](https://github.com/twistlock/sample-code/blob/7d089d5ad7ea1fb6de1facd96368f6feabfd2a3e/operators/twistlock-console-helm-operator/watches.yaml), which comes from [here](https://github.com/twistlock/sample-code/blob/1bbc1bada892d0665653a05226730b5472d5792c/operators/twistlock-console-helm-operator/deploy/7_operator.yaml#L32-L33).

I tried patching the deployment with
```bash
oc patch deployment deployment/prisma-cloud-compute-console-helm-operator -p '{"spec":{"template":{"spec":{"containers":[{"env":[{"name":"RELATED_IMAGE_CONSOLE","value":"registry-auth.twistlock.com/tw_xxxxxxxxxxxxx/twistlock/console:console_20_04_169"}],"name":"prisma-cloud-compute-console-helm-operator"}]}}}}'
```
but I am assuming that this is undone by the Helm template. I've no idea how to use this operator right now.

**Comment by kitforbes** [comment]
Small folow up to say that I got the patch to work with the below command:
```bash
oc patch "clusterserviceversion/prisma-cloud-compute-console-operator.v1.0.0" \
  -n my-namespace \
  -p '{"spec":{"install":{"spec":{"deployments":[{"name":"prisma-cloud-compute-console-helm-operator","spec":{"selector":{"matchLabels":{"name":"prisma-cloud-compute-console-helm-operator"}},"template":{"spec":{"containers":[{"name":"prisma-cloud-compute-console-helm-operator","env":[{"name":"RELATED_IMAGE_CONSOLE","value":"registry-auth.twistlock.com/tw_xxxxxxxx/twistlock/console:console_20_04_169"}]}]}}}}]}}}}' \
  --type=merge \
  --dry-run=server
```
