### ISSUE TITLE
Prisma Cloud GitHub Actions

### ISSUE THREAD

**Issue by harisrini** [twistlock/sample-code#86]
Improvements to the GitHub actions we support today and how we can publish things on the GitHub Actions marketplace.

- [ ] Create formal GitHub Action
- [ ] Get it added to GitHub Marketplace

**Comment by wfg** [comment]
http://docs.oasis-open.org/sarif/sarif/v2.0/csprd01/sarif-v2.0-csprd01.html

**Comment by wfg** [comment]
https://github.com/marketplace/actions/prisma-cloud-scan
