### ISSUE TITLE
/siem/splunk/twistlock/bin/poll_forensics.py JSONDecodeError Error

### ISSUE THREAD

**Issue by mwilco03** [twistlock/sample-code#87]
Currently a race condition can occur if poll_incidents.py is ran twice and appends to forensics_file.txt 
It will result in the JSONDecodeError stated above.
This can be resolved by testing to see if the file exists. 
If it doesn't just write the file don't append to it. 
The following code should resolve this issue.

**Comment by wfg** [comment]
This is actually fixed in the latest commit 6 days ago: https://github.com/twistlock/sample-code/commit/38a56370f67ce387bc6637632d022f42d5bf0cdf

This change is included in 3.1.1.

**Comment by mwilco03** [comment]
I saw the fix. IMHO checking to see if the file is there and printing error is less than ideal.
The condition that the forensic_file.txt could be created and blank would result in error.
The condition that if something stops mid write could throw an error.

Checking the file attempting to marshal the data then processing it would be more resilient pattern than file exists quit. 
Ideally the same could be said for the polling of the forensic data.
Poping data off the array then writing the file to disk would result in resilience against an unwanted shutdown or emergency stopage.

**Comment by wfg** [comment]
>Checking the file attempting to marshal the data then processing it would be more resilient pattern than file exists quit.

Great point. Merged https://github.com/twistlock/sample-code/pull/88.
