### ISSUE TITLE
Prisma Compute Terraform Provider

### ISSUE THREAD

**Issue by donwukwe890** [twistlock/sample-code#90]
To extend the current Terraform provider to include Compute capabilities: https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud/latest/docs

**Comment by wfg** [comment]
@donwukwe890 What would you like the Terraform provider to do exactly?

**Comment by donwukwe890** [comment]
@wfg We have customers that have been asking for a provider to do things like create defenders, add registries and repos, create vulnerability rules, runtime rules. As much as possible but those would probably be the main things to start. I have about 3 customers that have asked for this capability in the last month.
